run:
  name: regression_frc_zero
time_stepping:
  NTIMES: 99540
  DT: 40.0
  NHIS: 90
structure:
  str_a: 0.016666666666666666
  depth_zero_below: 90.0
  CD: 0.63
  c4: 0.44
bodyforce:
  mode: uniform
  U0: 0.1
  V0: 0.0
  BFRC_TSTR: 0.0
  BFRC_TEND: 0.0
  BFRC_CD: 0.005
  BFRC_U: 315.0
  BFRC_V: 0.0
initial:
  ocean_time_seconds: 0.0
  temp_mode: tanh
  temp_T0: 20.0
  temp_dT: 10.0
  temp_zt: 40.0
  temp_ht: 10.0
  salt_S0: 35.0
  mode: uniform
  U0: 0.0
  V0: 0.0
  ubar0: 0.1
