# This is a test configuration file for the ROMS model, 
# specifically for testing the production part of STRUCTURE_MIXING option.
# Note that UV_BODYFORCE must be activated.

run:
  name: test_STRUCTURE_PRODUCTION

structure:
  str_a: 0.0001
  c4 : 0.6       # strong mixing

bodyforce:
  BFRC_U: 3.15

time_stepping:
  NTIMES: 60480   # want to reach steady state, so run for a month

initial:
  temp_dT: 0.0    # no shear
  ubar0: 0        # start from rest

GLS:        # k-epsilon closure, so gls = epsilon
  P: 3.0
  M: 1.5
  N: -1.0
  C1: 1.44
  C2: 1.92
  C3M: -0.63
  C3P : 1.0
  SIGK: 2
  SIGP: 1.3

