# This is a test configuration file for the ROMS model, 
# specifically for testing the drag part of STRUCTURE_MIXING option.
# Note that UV_BODYFORCE must be activated.
# Running this should result in flow in the
#  x-direction, with a mean velocity of 0.1 m/s when
# steady state is reached.

run:
  name: test_STRUCTURE_DRAG

structure:
  str_a: 0.0001

bodyforce:
  BFRC_U: 3.15

time_stepping:
  NTIMES: 30240