# This is a test configuration file for the ROMS model,
# specifically for testing the UV_BODYFORCE option.
# Running this should result in a uniform flow in the
# x-direction, approaching a steady-state velocity of
# U0 = 0.1 m/s exponentially (rate BFRC_CD) over time.

run:
  name: test_UV_BODYFORCE

structure:
  str_a: 0.0

bodyforce:
  mode: uniform
  U0: 0.1
  V0: 0.0

time_stepping:
  NTIMES: 2160
