# This is a test configuration file for the ROMS model, 
# specifically for testing the UV_BODYFORCE option. 
# Running this should result in a uniform flow in the
#  x-direction, with a velocity increasing linearly 
# in time, reaching 0.1 m/s after 1 day 
# of simulation time.

run:
  name: test_UV_BODYFORCE

structure:
  str_a: 0.0

bodyforce:
  BFRC_U: 11.57

time_stepping:
  NTIMES: 2160 